# This file was generated by GoReleaser. DO NOT EDIT.
class EzCgi < Formula
  desc "A flexible and easy to use CGI HTTP server."
  homepage "https://github.com/raphaelreyna/ez-cgi/tree/master/cmd"
  version "0.7.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/raphaelreyna/ez-cgi/releases/download/v0.7.2/ez-cgi_0.7.2.macos_x86_64.tar.gz"
    sha256 "8d28f926579a0e18d58aaa04e0be7d575eed17ae089b8d6e6dffaf2d6224beda"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/raphaelreyna/ez-cgi/releases/download/v0.7.2/ez-cgi_0.7.2.linux_x86_64.tar.gz"
      sha256 "0bf890c8295058dfe09e105db454a57923ee931c4f28baa9d39d4f6c08da00c1"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raphaelreyna/ez-cgi/releases/download/v0.7.2/ez-cgi_0.7.2.linux_arm64.tar.gz"
        sha256 "3092fe4406dba356cea25858dc455ab06225aa21671f5404b8bb0fef928a99fa"
      else
        url "https://github.com/raphaelreyna/ez-cgi/releases/download/v0.7.2/ez-cgi_0.7.2.linux_arm.tar.gz"
        sha256 "f4bf5014f97a82a23159118eace1b981c3dac64f322ef171ad083da3af4930e2"
      end
    end
  end

  def install
    bin.install "ez-cgi"
  end
end
